### ISSUE TITLE
老大，有下面的报错。

### ISSUE THREAD

**Issue by liuts** [mayiweb/goctp#10]
我百度到，问题可能是：代码commit后，手工把goctp替换github.com/mayiweb/goctp造成的

github.com/mayiweb/goctp: github.com/mayiweb/goctp@v0.0.0-20220422143449-1057fdab846a: parsing go.mod:
	module declares its path as: goctp
	        but was required as: github.com/mayiweb/goctp
![image](https://user-images.githubusercontent.com/8000832/164877951-c6c06df2-a85c-43c4-898d-a91e50ffb5e1.png)

系统版本：centos7     
 go version： go1.16.13

**Comment by mayiweb** [comment]
删除工作目录下的原 goctp 及缓存，重新下载试试
